# Number of labels to fetch (optional). Defaults to 20.
numLabels: 40

# Determines if we search the title (optional). Defaults to true.
matchTitle: true

# Determines if we search the body (optional). Defaults to true.
matchBody: true

# Explicit keyword mappings to labels. Form of match:label. Required.
labelMappings:
    "[WIP]": WIP
    "academy": academy
    "tutorial": academy
    "Tutorial": academy
    "lm": apollo-lm
    "lem": apollo-lm
    "LM": apollo-lm
    "LEM": apollo-lm
    "csm": apollo-csm
    "CSM": apollo-csm
    "cm": apollo-csm
    "CM": apollo-csm
    "mercury": mercury
    "Mercury": mercury
    "gemini": gemini
    "Gemini": gemini
    "typo": typo
    "Typo": typo
    "typos": typo
    "Typos": typo
    "guidance": guidance
    hooks: documentation
